### ISSUE TITLE
サインアウトできない

### ISSUE THREAD

**Issue by KaitoWatanabe** [litmon/css-puzzle#32]

**Comment by KaitoWatanabe** [comment]
facebookログイン中 ログアウトをすると
`No route matches [POST] "/users/sign_out"`
とエラーが表示される

**Comment by litmon** [comment]
DELETEで送らないといけないのにPOSTで送ってるから悪いっぽい。
すぐ直しますのでもう少しお待ちを！

**Comment by KaitoWatanabe** [comment]
:+1:
